### ISSUE TITLE
Crash in shifter zerus.

### ISSUE THREAD

**Issue by jeremysalwen** [JDBumgardner/stone_ground_hearth_battles#36]
```
Traceback (most recent call last):
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/training/pytorch/ppo.py", line 418, in <module>
    main()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/training/pytorch/ppo.py", line 414, in main
    ppo_learner.run()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/training/pytorch/ppo.py", line 345, in run
    worker.play_game()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/training/pytorch/worker.py", line 44, in play_game
    host.play_game()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/host/round_robin_host.py", line 61, in play_game
    self.play_round()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/host/round_robin_host.py", line 52, in play_round
    for _ in self.play_round_generator():
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/host/round_robin_host.py", line 27, in play_round_generator
    self.tavern.buying_step()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/tavern.py", line 59, in buying_step
    player.buying_step()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/player.py", line 103, in buying_step
    self.broadcast_buy_phase_event(events.BuyStartEvent())
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/player.py", line 292, in broadcast_buy_phase_event
    card.handle_event_in_hand(event, BuyPhaseContext(self, randomizer or self.tavern.randomizer))
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/cards.py", line 173, in handle_event_in_hand
    self.zerus_shift(context)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/cards.py", line 241, in zerus_shift
    context.owner.remove_hand_card(self)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/hearthstone/simulator/core/player.py", line 344, in remove_hand_card
    self._hand.remove(card)
ValueError: list.remove(x): x not in list

Process finished with exit code 1
```

**Comment by ethansaxenian** [comment]
Do we know the boardstate when this happened?

**Comment by ethansaxenian** [comment]
Actually, there could've been a second shifter zerus in hand that caused a golden transformation, removing the first zerus from hand.

**Comment by ethansaxenian** [comment]
But it looks like we're not even checking for a golden transformation after a zerus shift (I suppose we probably should be?), so that's not it.

**Comment by ethansaxenian** [comment]
> But it looks like we're not even checking for a golden transformation after a zerus shift (I suppose we probably should be?), so that's not it.

Oh wait ignore that ^

**Comment by JDBumgardner** [comment]
Is this a very rare bug?

**Comment by jeremysalwen** [comment]
Yes, this is pretty rare, it happened after 122 million actions were taken.

**Comment by ethansaxenian** [comment]
AHA! This test fails:

```
    class TestZerusBugRandomizer(DefaultRandomizer):
        def select_draw_card(self, cards: List['MonsterCard'], player_name: str, round_number: int) -> 'MonsterCard':
            if round_number <= 3:
                return force_card(cards, AlleyCat)
            return force_card(cards, ShifterZerus)

        def select_random_minion(self, cards: List['Type'], round_number: int) -> 'Type':
            if round_number == 5:
                return AlleyCat
            elif round_number == 6:
                return DragonspawnLieutenant
            elif round_number == 7:
                return ShifterZerus
            else:
                return cards[0]

    def test_zerus_bug(self):
        tavern = Tavern(restrict_types=False)
        tavern.randomizer = self.TestZerusBugRandomizer()
        player_1 = tavern.add_player_with_hero("Dante_Kong")
        player_2 = tavern.add_player_with_hero("lucy")
        self.upgrade_to_tier(tavern, 3)
        tavern.buying_step()
        player_1.purchase(StoreIndex(0))
        self.assertCardListEquals(player_1.hand, [ShifterZerus])
        tavern.combat_step()
        tavern.buying_step()
        player_1.purchase(StoreIndex(0))
        self.assertCardListEquals(player_1.hand, [AlleyCat, ShifterZerus])
        tavern.combat_step()
        tavern.buying_step()
        player_1.purchase(StoreIndex(0))
        self.assertCardListEquals(player_1.hand, [DragonspawnLieutenant, DragonspawnLieutenant, ShifterZerus])
        tavern.combat_step()
        tavern.buying_step()
```

**Comment by ethansaxenian** [comment]
```
Error
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/tests/test_tavern.py", line 3217, in test_zerus_bug
    tavern.buying_step()
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/tavern.py", line 59, in buying_step
    player.buying_step()
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 105, in buying_step
    self.broadcast_buy_phase_event(events.BuyStartEvent())
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 305, in broadcast_buy_phase_event
    card.handle_event_in_hand(event, BuyPhaseContext(self, randomizer or self.tavern.randomizer))
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/card_pool.py", line 37, in handle_event_in_hand
    self.zerus_shift(context)
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/cards.py", line 248, in zerus_shift
    context.owner.remove_hand_card(self)
  File "/Users/ethansaxenian/Documents/GitHub/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 357, in remove_hand_card
    self._hand.remove(card)
ValueError: list.remove(x): x not in list
```

**Comment by ethansaxenian** [comment]
same error!

**Comment by ethansaxenian** [comment]
It looks like when the 2nd Dragon/Zerus transforms back into a Zerus, the golden transformation happens and the 3rd Zerus is removed from the hand, and then the handle_event loop continues onto the now-removed 3rd Zerus. Is this how python is supposed to work?

**Comment by JDBumgardner** [comment]
I missed this yesterday, Ethan. Good catch. 

I think it's because in broadcast buy phase event (player 300) we use player.in_play.copy(). It's because we don't want to mutate the lists while we're broadcasting to them in case we summon stuff and mess up the indices while we're iterating over them or send events to minions that we're just summoned. However, that means that if a minion is removed from the list then we still broadcast the event to it. Then when we call player.remove_hand_card(self) in zerus shift that attempts to remove the card from the player's hand, but it's not there anymore.

**Comment by JDBumgardner** [comment]
We could protect remove_hand_card with an if statement. more general might be for us to ask if the card in broadcast_buy_phase_event is in the actual list as well so we just don't broadcast events to cards that have been removed already.
