### ISSUE TITLE
Bot playing cards while dead

### ISSUE THREAD

**Issue by ethansaxenian** [JDBumgardner/stone_ground_hearth_battles#45]
It appears that a bot (not sure which one) somehow played a Vulgar Homunculus when it was already dead, resulting in the following exception.

Traceback (most recent call last):
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/training/pytorch/ppo.py", line 472, in <module>
    main()
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/training/pytorch/ppo.py", line 468, in main
    ppo_learner.run()
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/training/pytorch/ppo.py", line 385, in run
    Worker(learning_bot_contestant, other_contestants, self.hparams['game_size'], replay_buffer,
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/training/pytorch/worker/worker.py", line 49, in play_game
    host.play_game()
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/host/round_robin_host.py", line 68, in play_game
    self.play_round()
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/host/round_robin_host.py", line 59, in play_round
    for _ in self.play_round_generator():
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/host/round_robin_host.py", line 42, in play_round_generator
    self._apply_and_record(player_name, action, agent_annotation)
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/host/host.py", line 41, in _apply_and_record
    action.apply(self.tavern.players[player_name])
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/agent.py", line 122, in apply
    player.summon_from_hand(self.index, self.targets)
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 153, in summon_from_hand
    self.broadcast_buy_phase_event(events.SummonBuyEvent(card, target_cards))
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 337, in broadcast_buy_phase_event
    card.handle_event(event, BuyPhaseContext(self, randomizer or self.tavern.randomizer))
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/cards.py", line 174, in handle_event
    self.battlecry(event.targets, context)
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/card_pool.py", line 234, in base_battlecry
    context.owner.take_damage(2)
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 384, in take_damage
    self.resolve_death()
  File "/Users/ethansaxenian/Documents/Python/stone_ground_hearth_battles/hearthstone/simulator/core/player.py", line 473, in resolve_death
    assert not self.dead and self.health <= 0
AssertionError

**Comment by ethansaxenian** [comment]
I've gotten this error from Wrath Weaver as well
