### ISSUE TITLE
Value Error during Training

### ISSUE THREAD

**Issue by DistilledData** [JDBumgardner/stone_ground_hearth_battles#58]
How to Reproduce: Run on Windows 10 for uncertain amount of time
Error Traceback:

Traceback (most recent call last):
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\ppo.py", line 708, in <module>
    main()
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\ppo.py", line 704, in main
    ppo_learner.run()
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\ppo.py", line 358, in run
    worker_pool.play_games(learning_bot_contestant, other_contestants, self.hparams['game_size'])
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\worker\single_machine\worker_pool.py", line 118, in play_games
    replay = self._get_task_result(promise)
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\worker\single_machine\worker_pool.py", line 83, in _get_task_result
    return promise.result()
  File "AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\training\pytorch\worker\single_machine\worker_pool.py", line 38, in play_game
    host.play_game()
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\host\round_robin_host.py", line 74, in play_game
    self.play_round()
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\host\round_robin_host.py", line 65, in play_round
    for _ in self.play_round_generator():
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\host\round_robin_host.py", line 46, in play_round_generator
    self._apply_and_record(player_name, action, agent_annotation)
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\host\host.py", line 41, in _apply_and_record
    action.apply(self.tavern.players[player_name])
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\agent\actions.py", line 129, in apply
    player.summon_from_hand(self.index, self.targets)
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\core\player.py", line 165, in summon_from_hand
    self.broadcast_buy_phase_event(events.SummonBuyEvent(card, target_cards))
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\core\player.py", line 373, in broadcast_buy_phase_event
    card.handle_event(event, BuyPhaseContext(self, randomizer or self.tavern.randomizer))
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\core\cards.py", line 162, in handle_event
    self.battlecry(event.targets, context)
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\core\card_pool.py", line 1771, in base_battlecry
    count = len(one_minion_per_type(context.owner.in_play, context.randomizer, excluded_card=self)) * (
  File "PycharmProjects\stone_ground_hearth_battles\hearthstone\simulator\core\cards.py", line 26, in one_minion_per_type
    restricted_cards.remove(excluded_card)
ValueError: list.remove(x): x not in list

Process finished with exit code 1

**Comment by ethansaxenian** [comment]
Just pushed a commit that should fix this
